name: drone_checklist
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.4.0
  http: ^1.2.2
  path_provider: ^2.1.5
  dio: ^5.7.0
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.5
  dquery: ^3.0.0+1
  json_annotation: ^4.9.0
  built_value: ^8.9.2
  built_value_generator: ^8.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true




